[package]
name = "sqlite-hello"
version = "0.1.0-alpha.71"
license = "MIT OR Apache"
homepage = "https://alexgarcia.xyz/sqlite-hello"
repo = "https://github.com/asg017/sqlite-hello"
description = "A hello SQLite extension to test sqlite-dist."
authors = ["Alex Garcia"]

[targets]
github_releases = {}
sqlpkg = {}
spm = {}

pip = {}
datasette = {}
sqlite_utils = {}

npm = {}

gem = { module_name="SqliteHello" }
